# Generated by Django 5.2.5 on 2025-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuntimeExecution',
        ),
    ]
