# Generated by Django 5.2.5 on 2025-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_workernode_remove_function_code_path_function_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
